#!/usr/bin/env python3
"""
chr_to_gba.py — convert the original game's NES tile graphics into GBA tiles.

This repo ships no game art: the real 8x8 graphics live in the cartridge's
CHR ROM, which isn't ours to distribute. If you have a dump of the original
(the disassembly project calls it `clean.nes`), this converts its tiles into
a C header the GBA build can compile in, replacing the placeholder shapes
that `gba/main.c` generates at runtime.

    python3 tools/chr_to_gba.py clean.nes -o gba/tiles_game.h
    python3 tools/chr_to_gba.py --self-test      # no ROM needed

Format notes, since the two consoles disagree on almost everything:

  NES CHR is 2 bits per pixel, stored PLANAR: 16 bytes per tile, the first 8
  holding bit 0 of each row and the next 8 holding bit 1. A pixel's value is
  0-3, an index into whichever 4-colour palette the attribute table selects.

  GBA 4bpp is 32 bytes per tile, stored PACKED: two pixels per byte, low
  nibble first, each a 0-15 index into a 16-colour bank.

So the conversion is a planar-to-packed repack plus a widening of 2-bit
values to 4-bit ones. The NES's four colours land on GBA indices 0-3, which
is exactly the layout gba/palette.h sets up per piece — colour 0 stays the
shared transparent backdrop.

The Tengen cartridge holds 16KB of CHR in four 4KB tilesets, in this order
(reference/disasm/entry.asm.txt): game, dancers, title, various. --tileset
picks one; the default is the game tileset, which is what the playfield uses.
"""
import argparse
import sys

NES_HEADER = 16
NES_TILE_BYTES = 16
GBA_TILE_BYTES = 32
TILESET_BYTES = 4096
TILESETS = ["game", "dancers", "title", "various"]


def chr_from_nes(data: bytes) -> bytes:
    """Slice the CHR ROM out of an iNES file."""
    if data[:4] != b"NES\x1a":
        raise ValueError("not an iNES file (missing NES\\x1a magic)")
    prg_banks, chr_banks = data[4], data[5]
    if chr_banks == 0:
        raise ValueError("this ROM uses CHR RAM, so there are no tiles to extract")
    start = NES_HEADER + prg_banks * 16384
    end = start + chr_banks * 8192
    if len(data) < end:
        raise ValueError(f"file is truncated: expected at least {end} bytes, got {len(data)}")
    return data[start:end]


def tile_2bpp_to_pixels(tile: bytes) -> list:
    """One 16-byte NES tile -> 64 pixel values (0-3), row-major."""
    pixels = []
    for row in range(8):
        plane0, plane1 = tile[row], tile[row + 8]
        for bit in range(7, -1, -1):  # leftmost pixel is the HIGH bit
            pixels.append(((plane0 >> bit) & 1) | (((plane1 >> bit) & 1) << 1))
    return pixels


def pixels_to_gba_4bpp(pixels: list) -> bytes:
    """64 pixel values -> 32 bytes of GBA 4bpp, two pixels per byte, low first."""
    out = bytearray()
    for i in range(0, 64, 2):
        out.append((pixels[i] & 0xF) | ((pixels[i + 1] & 0xF) << 4))
    return bytes(out)


def convert(chr_data: bytes) -> bytes:
    out = bytearray()
    for offset in range(0, len(chr_data), NES_TILE_BYTES):
        tile = chr_data[offset:offset + NES_TILE_BYTES]
        if len(tile) < NES_TILE_BYTES:
            break
        out += pixels_to_gba_4bpp(tile_2bpp_to_pixels(tile))
    return bytes(out)


def emit_header(gba_tiles: bytes, name: str, source: str) -> str:
    count = len(gba_tiles) // GBA_TILE_BYTES
    lines = [
        "/*",
        f" * {name}.h — GBA tile data converted from the original NES CHR ROM.",
        " *",
        " * GENERATED by tools/chr_to_gba.py — do not edit by hand.",
        f" * Source tileset: {source} ({count} tiles).",
        " *",
        " * This file contains game artwork extracted from a cartridge dump you",
        " * supplied. Whether you can redistribute it is a question about that",
        " * artwork, not about this converter — so it is generated locally and",
        " * left out of version control by default.",
        " */",
        f"#ifndef {name.upper()}_H",
        f"#define {name.upper()}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {name.upper()}_TILE_COUNT {count}",
        "",
        f"static const uint8_t {name}[{len(gba_tiles)}] = {{",
    ]
    for i in range(0, len(gba_tiles), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in gba_tiles[i:i + 16])
        lines.append(f"    {chunk},")
    lines += ["};", "", f"#endif /* {name.upper()}_H */", ""]
    return "\n".join(lines)


def self_test() -> int:
    """Checks the format conversion against hand-worked cases, so the tool can
    be trusted before anyone points it at a ROM."""
    failures = []

    # A tile whose plane 0 is all ones and plane 1 all zeros is solid colour 1.
    solid1 = bytes([0xFF] * 8 + [0x00] * 8)
    if tile_2bpp_to_pixels(solid1) != [1] * 64:
        failures.append("plano 0 lleno deberia dar 64 pixeles de color 1")

    # Both planes set is solid colour 3.
    solid3 = bytes([0xFF] * 16)
    if tile_2bpp_to_pixels(solid3) != [3] * 64:
        failures.append("ambos planos llenos deberian dar color 3")

    # Empty tile is solid colour 0.
    if tile_2bpp_to_pixels(bytes(16)) != [0] * 64:
        failures.append("tile vacio deberia dar color 0")

    # Bit order: only the high bit of plane 0 set means the LEFTMOST pixel.
    left = bytes([0x80] + [0x00] * 7 + [0x00] * 8)
    px = tile_2bpp_to_pixels(left)
    if px[0] != 1 or any(px[1:]):
        failures.append("el bit alto deberia ser el pixel de la izquierda")

    # Packing: low nibble holds the left pixel of each pair.
    packed = pixels_to_gba_4bpp([1, 2] + [0] * 62)
    if packed[0] != 0x21:
        failures.append(f"empaquetado 4bpp invertido: 0x{packed[0]:02X}, esperado 0x21")

    # Sizes.
    if len(convert(solid3)) != GBA_TILE_BYTES:
        failures.append("un tile de NES deberia producir 32 bytes de GBA")

    if failures:
        for f in failures:
            print(f"FALLA: {f}")
        return 1
    print("OK: la conversion 2bpp planar -> 4bpp empaquetado es correcta.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("rom", nargs="?", help="iNES ROM dump, or a raw .chr file")
    ap.add_argument("-o", "--out", help="header file to write (default: stdout)")
    ap.add_argument("--tileset", choices=TILESETS, default="game")
    ap.add_argument("--name", default="kGameTiles", help="C identifier for the array")
    ap.add_argument("--self-test", action="store_true",
                    help="verify the format conversion without needing a ROM")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    if not args.rom:
        ap.error("give a ROM/CHR file, or --self-test")

    with open(args.rom, "rb") as fh:
        data = fh.read()

    chr_data = chr_from_nes(data) if data[:4] == b"NES\x1a" else data

    index = TILESETS.index(args.tileset)
    start = index * TILESET_BYTES
    if len(chr_data) < start + TILESET_BYTES:
        print(f"aviso: el CHR tiene {len(chr_data)} bytes, menos de lo que "
              f"necesita el tileset '{args.tileset}'; se convierte lo que hay",
              file=sys.stderr)
        chunk = chr_data[start:]
    else:
        chunk = chr_data[start:start + TILESET_BYTES]

    header = emit_header(convert(chunk), args.name, f"{args.rom} [{args.tileset}]")
    if args.out:
        with open(args.out, "w") as fh:
            fh.write(header)
        print(f"escrito {args.out} ({len(chunk) // NES_TILE_BYTES} tiles)")
    else:
        print(header)
    return 0


if __name__ == "__main__":
    sys.exit(main())
