#!/usr/bin/env python3
"""THE GAME BOY PLAYER'S LOGO, from a picture of it you supply.

    python3 tools/make_gbp_logo.py gbp_logo.png [-o gba/gbp_logo.h]

The Player recognises a game by the logo on its screen at boot (GBATEK,
"GBA Gameboy Player": 240x160, 44 colours, tiled or bitmap alike), so the
picture has to be the logo exactly: a lossless 240x160 capture of a game
that shows it — Drill Dozer, Pokemon Pinball, Super Mario Advance 4 — from
mGBA, whose 8-bit channels are the console's 5-bit ones widened, so they
narrow back exactly. It is Nintendo's art: like the cartridge's graphics the
header is generated and not committed (.gitignore), and without it the ROM
shows no logo and never looks for a Player (gba/gbp.c).

The header holds the palette (the background first) and the logo's
bounding box, one byte a pixel, for Mode 4.
"""
import argparse
import sys

from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("-o", "--out", default="gba/gbp_logo.h")
    args = ap.parse_args()

    im = Image.open(args.image).convert("RGB")
    if im.size != (240, 160):
        sys.exit(f"{args.image}: {im.size}, not 240x160 — a whole screen, please")
    px = list(im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata())
    background = px[0]
    colours = [background] + sorted({c for c in px} - {background})
    if len(colours) > 256:
        sys.exit(f"{len(colours)} colours: not a GBA screen")
    index = {c: i for i, c in enumerate(colours)}

    xs = [i % 240 for i, c in enumerate(px) if c != background]
    ys = [i // 240 for i, c in enumerate(px) if c != background]
    x0, x1 = min(xs) & ~1, (max(xs) + 2) & ~1     # even: VRAM takes halfwords
    y0, y1 = min(ys), max(ys) + 1

    def gba(c):
        r, g, b = (v >> 3 for v in c)
        return r | (g << 5) | (b << 10)

    data = bytes(index[px[y * 240 + x]] for y in range(y0, y1) for x in range(x0, x1))
    with open(args.out, "w") as f:
        f.write("/* Generated by tools/make_gbp_logo.py from a picture you supplied.\n"
                " * Nintendo's art: not committed, see .gitignore. */\n")
        f.write(f"#define GBP_LOGO_X {x0}\n#define GBP_LOGO_Y {y0}\n")
        f.write(f"#define GBP_LOGO_W {x1 - x0}\n#define GBP_LOGO_H {y1 - y0}\n")
        f.write(f"#define GBP_LOGO_COLOURS {len(colours)}\n")
        f.write("static const unsigned short kGbpLogoPalette[GBP_LOGO_COLOURS] = {\n")
        for i in range(0, len(colours), 8):
            f.write("    " + ", ".join(f"0x{gba(c):04X}" for c in colours[i:i + 8]) + ",\n")
        f.write("};\n")
        f.write(f"static const unsigned char kGbpLogoPixels[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"{args.out}: {len(colours)} colours, {x1 - x0}x{y1 - y0} at ({x0},{y0})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
