#!/usr/bin/env python3
"""THE PUBLISHER'S LOGO FOR THE SPLASH SCREEN, from an image you supply.

    python3 tools/make_splash.py logo.png [-o gba/splash_logo.h] [--width 200]

The image (transparent or not) is laid on white, scaled to --width pixels
wide keeping its shape, and cut down to sixteen colours with white as
colour 0 (the screen's backdrop). The header holds the palette as GBA
colours and the picture four bits a pixel, two to a byte, the left one in
the low nibble. The logo is not the port's own art, so like the
cartridge's graphics the header is generated, not committed (.gitignore);
without it the ROM simply has no splash (gba/splash.c).
"""
import argparse
import sys

from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("-o", "--out", default="gba/splash_logo.h")
    ap.add_argument("--width", type=int, default=200)
    args = ap.parse_args()

    src = Image.open(args.image).convert("RGBA")
    white = Image.new("RGBA", src.size, (255, 255, 255, 255))
    flat = Image.alpha_composite(white, src).convert("RGB")
    w = args.width & ~1
    h = max(2, round(flat.height * w / flat.width)) & ~1
    small = flat.resize((w, h), Image.LANCZOS)
    q = small.quantize(colors=16, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    pal = q.getpalette()[:48]
    pal += [255] * (48 - len(pal))
    colours = [tuple(pal[3 * i:3 * i + 3]) for i in range(16)]
    # White to index 0: the entry nearest it swaps places with whatever is there.
    near = min(range(16), key=lambda i: sum((255 - c) ** 2 for c in colours[i]))
    order = list(range(16))
    order[0], order[near] = order[near], order[0]
    remap = {old: new for new, old in enumerate(order)}
    colours = [colours[order[i]] for i in range(16)]
    colours[0] = (255, 255, 255)
    px = [remap[p] for p in q.get_flattened_data()] if hasattr(q, "get_flattened_data") \
        else [remap[p] for p in q.getdata()]

    def gba(c):
        r, g, b = (v >> 3 for v in c)
        return r | (g << 5) | (b << 10)

    data = bytes(px[i] | (px[i + 1] << 4) for i in range(0, len(px), 2))
    with open(args.out, "w") as f:
        f.write("/* Generated by tools/make_splash.py from a logo you supplied. Not\n"
                " * committed: see .gitignore. */\n")
        f.write(f"#define SPLASH_W {w}\n#define SPLASH_H {h}\n")
        f.write("static const unsigned short kSplashPalette[16] = {\n    ")
        f.write(", ".join(f"0x{gba(c):04X}" for c in colours))
        f.write("\n};\n")
        f.write(f"static const unsigned char kSplashPixels[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"{args.out}: {w}x{h}, {len(data)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
