/*
 * nes_audio.h — the game's real music and sound effects on GBA.
 *
 * HOW THIS WORKS, because it is not the obvious approach:
 *
 * The port does NOT reimplement Tengen's sound engine. It runs it. The
 * engine is a dense piece of 6502 — vibrato, portamento, per-channel
 * envelopes, a sound-effect priority system that decides which of four
 * channels an effect may steal from the music — spread over a thousand-odd
 * lines of `reference/disasm/main.asm.txt` and working almost entirely
 * through unlabelled RAM. Transcribing it by hand would have meant guessing,
 * and this project's rule is that nothing gets guessed (../CLAUDE.md).
 *
 * So `gba/nes6502.c` is a small 6502 interpreter, `gba/audio_prg.h` is the
 * slice of the cartridge that holds the engine and every note of its music
 * (generated by tools/extract_assets.py, measured rather than guessed), and
 * this layer turns the NES APU writes that come out into GBA sound
 * registers. The music, the effects, and the way they interrupt each other
 * are the cartridge's own, frame for frame.
 *
 * It is affordable because the engine is small: ~600 6502 instructions per
 * frame typical, ~2300 in its worst frame, and the interpreter runs from
 * internal WRAM (see IWRAM_CODE and the .iwram section in gba.ld).
 *
 * What is NOT identical is the sound hardware. The NES APU and the GBA's PSG
 * are close relatives — two pulse channels with the same four duty cycles, a
 * noise channel, and a wave channel that can hold a triangle — but not the
 * same chip, so the translation in nes_audio.c is a mapping, documented
 * there, rather than an emulation of the APU itself.
 */
#ifndef NES_AUDIO_H
#define NES_AUDIO_H

#include <stdint.h>
#include <stdbool.h>

/* Track ids, from reference/disasm/constants.asm.txt:37-61. Passed straight
 * to the cartridge's own setMusicOrSoundEffect. */
#define NES_MUSIC_SUSPEND      0x01
#define NES_MUSIC_RESUME       0x02
#define NES_MUSIC_LOGINSKA     0x04
#define NES_MUSIC_BRADINSKY    0x05
#define NES_MUSIC_KARINKA      0x06
#define NES_MUSIC_TROIKA       0x07
#define NES_MUSIC_SILENCE      0x08
#define NES_MUSIC_TITLESCREEN  0x09
#define NES_MUSIC_GAMEOVER     0x0A
#define NES_MUSIC_LEVELUP      0x0D
#define NES_SOUND_DROP         0x0E
/* The cartridge's own sound engine can play these and the cartridge never
 * asks it to — constants.asm.txt marks $0F-$12 "maybe unused". The title's
 * skin easter egg uses CHIRP, so the egg has a voice nothing else in the game
 * uses, and it is still the ROM's voice. */
#define NES_SOUND_CHIRP        0x10
#define NES_SOUND_LINECLEAR    0x13
#define NES_SOUND_MENU_SELECT  0x14
#define NES_SOUND_SCREEN_SWITCH 0x15
#define NES_SOUND_TOPOUT       0x16

/* Sets up the GBA's sound hardware and the emulated engine. Call once. */
void nes_audio_init(void);

/* Queues a track or sound effect, exactly as the game's own code does when it
 * calls setMusicOrSoundEffect. */
void nes_audio_play(uint8_t track_id);

/* Runs one frame of the engine and applies what it wrote. Call once per
 * frame, at the same rate the NES called it from its NMI. */
void nes_audio_frame(void);

/* ----------------------------------------------------------------------- *
 * THE CARTRIDGE'S MACHINE, for the other things that run on it.
 *
 * The sound engine is not the only piece of the ROM the port executes rather
 * than imitates: the title screen's cathedral overlay and its fireworks are
 * too (see audio_prg.h, and the note beside draw_title_sprites in main.c).
 * They are not a second emulator. They are the SAME 6502, the same PRG slice
 * and the same 2KB of RAM, because on the cartridge they are one program —
 * the fireworks call setMusicOrSoundEffect for their bursts, so a burst on a
 * separate machine would be silent.
 *
 * These two functions are the whole interface: run one of the ROM's
 * subroutines to its RTS, and reach the RAM it worked in.
 * ----------------------------------------------------------------------- */
bool nes_rom_call(uint16_t addr, uint8_t a, uint32_t max_steps);
uint8_t *nes_rom_ram(void);

#endif /* NES_AUDIO_H */
